---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_patterns:
- "**/*.test.js"
